### ISSUE TITLE
foreign date

### ISSUE THREAD

**Issue by dcrystalj** [onysos/django-composite-foreignkey#1]
Is it possible to have CompositeForeignKey based on date range. On foreign table i have date ```from``` and ```to``` and on this table i have date. This date have to match as well.

**Comment by ornoone** [comment]
hi dcrystalj,

it should be possible to set the CompositeForeignKey for DateField as well as IntegerField or CharField. I just didn't tried it. have you tested it with your setup ? did it return an error ?

**Comment by dcrystalj** [comment]
i was thinking about date range from to. not mapping to specific column.
never mind, i will not need it
