### ISSUE TITLE
I am getting error unexpected keyword argument virtual only

### ISSUE THREAD

**Issue by Umartahir93** [onysos/django-composite-foreignkey#12]
![capture1](https://user-images.githubusercontent.com/31737085/36528804-2c6be6b6-17d8-11e8-9259-15ea2f242f43.JPG)
 This is my code

![capture](https://user-images.githubusercontent.com/31737085/36528828-40a2cb72-17d8-11e8-841b-b71def2d4112.JPG)

**Comment by ornoone** [comment]
hi @Umartahir93, sorry for the loooong delay, but can you provide which version of django you are using ?
