### ISSUE TITLE
migrations issue.

### ISSUE THREAD

**Issue by leslie89xlxiao** [onysos/django-composite-foreignkey#6]
Why it always generate a new migration file?

**Comment by vstoykov** [comment]
Can you please provide more context about your problem?

**Comment by adamstep** [comment]
I'm seeing the same issue. Every time I run `makemigrations`, A new migration file is generated to add the composite key field. So for some reason, Django doesn't understand that the migration has already been created.

**Comment by ornoone** [comment]
thanks for your help.
