### ISSUE TITLE
Migration's SQL empty

### ISSUE THREAD

**Issue by vrocha** [onysos/django-composite-foreignkey#8]
I added the following CompositeForeignKey to my models and when running sqlmigrate to see the SQL generated by that migration the output is blank.

`    host_taxonomy = CompositeForeignKey(PrimhosttaxMsw05, on_delete=models.SET_NULL, related_name='primate', to_fields={'taxcode_id': 'taxcode_id', 'hostreportedname': 'hostreportedname'}, null=True)`

Operating System: Ubuntu 16.04
Local Setup: Django 1.8.18 and python 3.5.2
Steps to reproduce:
1) Add CompositeForeignKey to one of your models.
2) python manage.py makemigrations {app} 
3) python sqlmigrate {app} {migration num} 

Expected result: The SQL needed to create a composite foreignkey is printed to the screen
Actual Result: sqlmigrate prints nothing at all.

The reason this is a problem is because my ForeignKey is not created at the database level.

**Comment by ornoone** [comment]
hi @vrocha, 

short response: CompositeForeignKey don't create constraints at database level.

long response: 
the CompositeForeignKey don't create a dedicated column in the database, nor update one. it's just a wrapper that use 2 existings columns (with their own db column and migrations) to build a query using this 2 fields.

did the query work as espected ? (migrate && ORM query)

**Comment by vrocha** [comment]
Ah, I really expected the constrain to be created by this field. I manually created the constrain, and the queries do work as expected. I am having the same issue as others where there is a new migration for my composite key every time I run makemigrations.

Thanks!

**Comment by ornoone** [comment]
this is a lot of work to do, since AFAIK django don't support «create multiple foreign key» migration action. but you can post your query for other to run it, or feel free to make a PR with this migration instruction :)


> I am having the same issue as others where there is a new migration for my composite key every time I run makemigrations.

I merged the fix this morning. you can do something like ```pip install -e git+https://github.com/onysos/django-composite-foreignkey#egg=django-composite-foreignkey```

**Comment by vrocha** [comment]
@ornoone Yes, I will try to make some sort of contribution to this project tonight or sometime this week or weekend. Thanks, again.
