### ISSUE TITLE
Can this be used in the Django admin?

### ISSUE THREAD

**Issue by vrocha** [onysos/django-composite-foreignkey#9]
I know this is not really an issue but I didn't see anything in the documentation on this topic.

**Comment by ornoone** [comment]
it's usable as any other ForeignKey, django's magic apply in this case and will build the correct query. 
just remember that there is no database field behind this field. so no mymodel**_id**

**Comment by vrocha** [comment]
Well, I tried making this a raw field id, and it threw an error. Also, I was only able to get it to show up on the list page.

**Comment by ornoone** [comment]
raw id field fail is because there is no field behind this FK
for the edit form, you can still show the fields composing this FK. in fact, no widget support to select among 2 values as pk, so this should not work in edit form. If you build your own, I can merge it in this lib :)

**Comment by vrocha** [comment]
Will do
